# Generated by Django 5.1.6 on 2025-04-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_dashboard_users_dashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='Notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
