# Generated by Django 5.1.6 on 2025-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dashboard_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
